# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: learn-github-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # - name: Restore dependencies
    #   working-directory: App
    #   run: dotnet restore
    # - name: Build
    #   working-directory: App
    #   run: dotnet build --no-restore
    # - name: Test
    #   working-directory: App
    #   run: dotnet test --no-build --verbosity normal
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #  # Build the Docker image
    # - name: Build Docker image
    #   working-directory: App
    #   run: |
    #     docker build -t aspifyapp:latest -f DockerFile .
    #     docker tag aspifyapp dedsec007/aspifyapp:version1

    #   # Push Docker image to Docker Hub
    # - name: Push Docker image
    #   run: |
    #     docker push dedsec007/aspifyapp:version1

    - name: Add SSH key
      id: add_ssh_key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Provide passphrase to ssh-add
      run: |
        echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add -
    # - name: Add SSH Key to known host
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan -H 34.35.59.101 >> ~/.ssh/known_hosts
    - name: Deploy to server
      run: |
          ssh -v raitrafiorenana_rambeloson@34.35.59.101 'echo "SSH connection successful"'
        

