# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: learn-github-actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    # - name: Restore dependencies
    #   working-directory: App
    #   run: dotnet restore
    # - name: Build
    #   working-directory: App
    #   run: dotnet build --no-restore
    # - name: Test
    #   working-directory: App
    #   run: dotnet test --no-build --verbosity normal
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #  # Build the Docker image
    # - name: Build Docker image
    #   working-directory: App
    #   run: |
    #     docker build -t aspifyapp:latest -f DockerFile .
    #     docker tag aspifyapp dedsec007/aspifyapp:version1

    #   # Push Docker image to Docker Hub
    # - name: Push Docker image
    #   run: |
    #     docker push dedsec007/aspifyapp:version1

    - name: Set up SSH and add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 34.35.59.101 >> ~/.ssh/known_hosts
        
    # - name: Add SSH key to agent and provide passphrase
    #   env:
    #       SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
    #       SSH_KEY: ${{secrets.SSH_KEY}}
    #       SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    #   run: |
    #       ssh-agent -a $SSH_AUTH_SOCK > /dev/null
    #       echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
    #       echo "$SSH_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

    - name: Set up SSH and add host to known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 34.35.59.101 >> ~/.ssh/known_hosts

    - name: Add SSH key to agent
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
      run: |
          eval "$(ssh-agent -a $SSH_AUTH_SOCK)"
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
        
    - name: Deploy to server
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh -v raitrafiorenana_rambeloson@34.35.59.101 'echo "SSH connection successful"'
        

